-- AlterEnum
-- Add new TipoFactura values for SaaS pivot: SUSCRIPCION, RENOVACION, OVERRIDE, UPGRADE
ALTER TYPE "TipoFactura" ADD VALUE 'SUSCRIPCION';
ALTER TYPE "TipoFactura" ADD VALUE 'RENOVACION';
ALTER TYPE "TipoFactura" ADD VALUE 'OVERRIDE';
ALTER TYPE "TipoFactura" ADD VALUE 'UPGRADE';
