/**
 * Errores de dominio.
 * Fase 1.2 – Referencia: definicionDomainServices.md
 */

export {
  DomainError,
  SinHistorialLaboralError,
  SinTarifaVigenteError,
  HistorialLaboralSuperpuestoError,
  DeudaCeroError,
  MontoIncorrectoError,
  PagoDuplicadoError,
  PagoCartaPendienteError,
  RequisitosCartaNoCumplidosError,
  CartaNoPendienteError,
  EscudoNoConfiguradoError,
  UsuarioNoEncontradoError,
  UsuarioInactivoError,
  EstadoRequisitoMismoEstadoError,
  EstadoRequisitoMismaObligacionError,
  RequisitoTipoNoEncontradoError,
  CartaPendienteExistenteError,
  CartaNoEncontradaError,
  DocumentoNoEncontradoError,
  TipoDocumentoNoPermitidoError,
  MontoCartaNoConfiguradoError,
  CartaVigenteError,
  IntencionPagoNoEncontradaError,
  WompiNoConfiguradoError,
  BootstrapYaEjecutadoError,
  AlmacenamientoNoConfiguradoError,
  ArchivoSobrepasaTamanioError,
  FormatoArchivoNoPermitidoError,
  LimiteUsuariosExcedidoError,
  LimiteCartasExcedidoError,
  LimiteStorageExcedidoError,
  SuscripcionVencidaError,
  DowngradeSoloDiaCorteError,
  DowngradeUsoExcedeLimitesError,
} from './domain.errors';
